# portainer
portainer_host: "{{ hostvars['manager'].ansible_host }}"
portainer_api_url: "https://{{ portainer_host  }}:9443/api"
portainer_endpoint_name: charger
portainer_version: "2.32.0"

# kecloak
keycloak_host: "{{ hostvars['manager'].ansible_host }}"

# grafana
grafana_host: "{{ hostvars['manager'].ansible_host }}"

# postgres
postgres_version: "17.5"

# e.g. "refs/heads/main" or "refs/heads/refactor"
git_default_branch: "refs/heads/main"

