---
all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    swarm:
      children:
        manager:
          hosts:
            localhost:
              ansible_connection: local
              ansible_user: user
              ansible_python_interpreter: /usr/bin/python3

        database:
          hosts:
            localhost:

        apps:
          hosts:
            localhost:
