---
all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    swarm:
      hosts:
        dev:
          ansible_connection: local
          ansible_host: localhost
          ansible_user: user
          ansible_python_interpreter: /usr/bin/python3

      children:
        manager:
          hosts:
            dev:

        database:
          hosts:
            dev:

        apps:
          hosts:
            dev:
