---
- name: Create /srv/grafana directory with specific ownership
  become: true
  file:
    path: /srv/grafana/data/
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user | default(host_user) }}"
    mode: '0755'
