# Create a docker secret.
#
# Expected variables:
# - secret_name:    (string) name of the secret
# - secret_value:   (string) value of the secret
- name: Create Docker secret
  hosts: raspberrypi
  tasks:
    - name: "Create Docker secret for {{ secret_name }}"
      community.docker.docker_secret:
        name: "{{ secret_name }}"
        state: present
        secret: "{{ secret_value }}"

