---
all:
  hosts:
    localhost:
      ansible_connection: local
      portainer_host: pi4b
    raspberrypi:
      ansible_host: pi4b
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
      portainer_host: pi4b

  children:
    managers:
      hosts:
        raspberrypi:

    databases:
      hosts:
        raspberrypi:

    apps:
      hosts:
        raspberrypi:
