---

# stack_config_body:
#   env:
#     - name: "new"
#       value: "value"
#   prune: true
#   pullImage: false
#   repositoryAuthentication: true
#   repositoryPassword: "string"
#   repositoryUsernam: "string"
#   stackName: "string"

- name: Redeploy stack '{{ stack_name }} wit id '{{ stack_id }}'
  uri:
    validate_certs: false
    url: "{{ portainer_api_url }}/stacks/{{stack_id}}/git/redeploy?endpointId={{stack_endpoint_id}}"
    method: PUT
    headers:
      Authorization: "Bearer {{ portainer_token }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ stack_config_body }}"
  register: deploy_stack_result
