
# roles/portainer/tasks/stack/stack_list.yml
#
# Task: List Stacks
# 
# Expects:
#   stacks_list_filter (string): Filters to process on the stack list. Encoded as JSON (a map[string]string). 
#                                For example, {'SwarmID': 'jpofkc0i9uo9wtx1zesuk649w'} will only return stacks
#                                that are part of the specified Swarm cluster. 
#                                Available filters: EndpointID, SwarmID
# 
# Sets:
#   portainer_endpoint_id (int): The ID of the matched endpoint, used for stack deployment.
#
# Example:
#   - include_tasks: roles/portainer/tasks/endpoint_id.yml
#     vars:
#       portainer_endpoint_name: charger
#
- name: Get list of Portainer endpoints
  uri:
    validate_certs: false
    url: "{{ portainer_api_url }}/stacks?filters={{ stack_filters | urlencode }}"
    method: GET
    headers:
      Authorization: "Bearer {{ portainer_token }}"
    return_content: true
  register: portainer_stacks_json

#- name: Prints two lines of messages, but only if there is an environment value set
#  ansible.builtin.debug:
#    msg:
#    - "Result {{ portainer_stacks_json.json | to_nice_json }}"
