---

# stack_config_body:
#   autoUpdate:
#     forcePullImage: false
#     forceUpdate: false
#     interval: "1m30s"
#     jobID: "15"
#     webhook: "05de31a2-79fa-4644-9c12-faa67e5c49f0"
#   env:
#     - name: "NAME"
#       value: "value"
#   prune: true
#   repositoryAuthentication: true
#   repositoryReferenceName: "refs/heads/main"
#   repositoryPassword: "string"
#   repositoryUsername: "string"

- name: Redeploy stack '{{ stack_name }}' wit id '{{ stack_id }}'
  uri:
    validate_certs: false
    url: "{{ portainer_api_url }}/stacks/{{stack_id}}/git?endpointId={{stack_endpoint_id}}"
    method: POST
    headers:
      Authorization: "Bearer {{ portainer_token }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ stack_git_body }}"
  register: deploy_stack_result
