---
all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    swarm:
      hosts:
        raspberrypi:
          ansible_host: pi4b
          ansible_user: pi
          ansible_python_interpreter: /usr/bin/python3
          portainer_host: pi4b

      children:
        manager:
          hosts:
            raspberrypi:

        database:
          hosts:
            raspberrypi:

        apps:
          hosts:
            raspberrypi:
