---
all:
  hosts:
    pi4b:
      ansible_host: pi4b
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
      portainer_host: pi4b

    localhost:
      ansible_connection: local

  children:
    swarm:
      hosts:
        pi4b:

    manager:
      hosts:
        pi4b:

    database:
      hosts:
        pi4b:

    apps:
      hosts:
        pi4b:
