---
- name: Ensure the PostgreSQL database exists
  community.postgresql.postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_owner }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
    login_host: postgres.internal.swarm.network
    port: 5432
    state: present
  delegate_to: localhost
