version: "3.8"

services:
  db:
    image: "postgres:${POSTGRES_VERSION}-alpine"
    environment:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
       - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - charger-net
    secrets:
      - portainer_admin_password

secrets:
  postgres_password:
    external: true

volumes:
  db_data:
    driver: local

networks:
  charger-net:
    external: true