version: "3.8"

services:
  db:
    image: "postgres:${POSTGRES_VERSION}-alpine"
    environment:
      POSTGRES_PASSWORD: "test"
    volumes:
       - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - charger-net

volumes:
  db_data:
    driver: local

networks:
  charger-net:
    external: true