version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    configs:
      - prometheus_config:/etc/prometheus/prometheus.yml:ro
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.9.1
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    deploy:
      mode: global
      restart_policy:
        condition: any

configs:
  prometheus_config:
    external: true

volumes:
  prometheus_data:

networks:
  monitoring:
    driver: overlay
