version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
        mode: 0444
    volumes:
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - charger-net

  node-exporter:
    image: prom/node-exporter:v1.9.1
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - /:/host:ro,rslave
    ports:
      - target: 9100
        published: 9100
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: any

configs:
  prometheus_config:
    external: true

volumes:
  prometheus_data:

networks:
  charger-net:
    external: true
