- name: Ensure Postgres data dir exists
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Postgres stack
  copy:
    content: "{{ lookup('template', 'postgres-stack.yml.j2') }}"
    dest: /opt/postgres-stack.yml

- name: Deploy with Docker stack
  shell: docker stack deploy -c /opt/postgres-stack.yml postgres
