---
- name: Create /srv/postgres/config directory with specific ownership
  become: true
  file:
    path: /srv/postgres/config
    state: directory
    owner: "{{ charger_user }}"
    group: "{{ charger_user | default(charger_user) }}"
    mode: '0755'

- name: Copy and render init-multiple-db.sh template
  become: true
  template:
    src: init-multiple-db.sh.j2
    dest: /srv/postgres/config/init-multiple-db.sh
    owner: "{{ charger_user }}"
    group: "{{ charger_user | default(charger_user) }}"
    mode: '0755'

- name: Create /srv/postgres/config directory with specific ownership
  become: true
  file:
    path: /srv/postgres/data
    state: directory
    owner: "{{ charger_user }}"
    group: "{{ charger_user | default(charger_user) }}"
    mode: '0755'
