- name: Create self-signed certificate
  hosts: localhost
  collections:
    - community.crypto

  vars:
    cert_hostname: "pi4b"
    cert_base_path: "{{ playbook_dir }}/../files/dev_cert"
    csr_path: "{{ cert_base_path }}/{{ cert_hostname }}.csr"
    cert_path: "{{ cert_base_path }}/{{ cert_hostname }}.crt"
    key_path: "{{ cert_base_path }}/{{ cert_hostname }}.key"

  tasks:
  - name: Generate a private key
    community.crypto.openssl_privatekey:
      path: "{{ key_path }}"
      size: 2048
      type: RSA
      mode: '0600'

  - name: Generate a certificate signing request (CSR)
    community.crypto.openssl_csr:
      path: "{{ csr_path }}"
      privatekey_path: "{{ key_path }}"
      common_name: "{{ cert_hostname }}"
      country_name: US
      state_or_province_name: California
      locality_name: San Francisco
      organization_name: MyOrg
      organizational_unit_name: IT
      mode: '0644'

  - name: Generate a self-signed certificate from CSR
    community.crypto.x509_certificate:
      path: "{{ cert_path }}"
      privatekey_path: "{{ key_path }}"
      csr_path: "{{ csr_path  }}"
      provider: selfsigned
      selfsigned_version: 3
      selfsigned_not_after: "+3650d"
      selfsigned_not_before: "+0s"
      selfsigned_digest: sha256
      selfsigned_create_subject_key_identifier: create_if_not_provided
      unsafe_writes: false
      mode: '0644'

    #- name: Generate a private key
    #  community.crypto.openssl_privatekey:
    #    path: "{{ key_path }}"
    #    size: 2048
    #    type: RSA
    #    mode: '0600'

    #- name: Generate a self-signed certificate
    #  community.crypto.x509_certificate:
    #    path: "{{ cert_path }}"
    #    privatekey_path: "{{ key_path }}"
    #    provider: selfsigned
    #    selfsigned_version: 3
    #    selfsigned_not_after: "+3650d"
    #    selfsigned_not_before: "+0s"
    #    selfsigned_digest: sha256
    #    selfsigned_create_subject_key_identifier: create_if_not_provided
    #    unsafe_writes: false  # disable chattr usage
    #    mode: '0644'
    #    subject:
    #      common_name: "{{ cert_hostname }}"
    #      country_name: US
    #      state_or_province_name: California
    #      locality_name: San Francisco
    #      organization_name: MyOrg
    #      organizational_unit_name: IT

    #- name: Change ownership of cert and key files to the playbook user
    #  file:
    #    path: "{{ item }}"
    #    owner: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    #    group: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    #  loop:
    #    - "{{ cert_path }}"
    #    - "{{ key_path }}"
    #  become: true
#
    #- name: Check cert validity
    #  shell: "openssl x509 -in {{ cert_path }} -noout -text"
    #  register: cert_info
    #  changed_when: false
#
    #- debug:
    #    var: cert_info.stdout_lines
