#- name: Deploy Portainer Stack
#  hosts: manager
#  become: true
#  
#  roles:
#    - portainer

- name: Prepare host portainer is deployed on
  hosts: manager
  tasks:
    - include_tasks: ../roles/portainer/tasks/prepare_host.yml

- name: Setup agent network
  hosts: manager
  tasks:
    - include_tasks: ../roles/portainer/tasks/create_agent_network.yml

- name: Deploy agents
  hosts: swarm
  tasks:
    - include_tasks: ../roles/portainer/tasks/deploy_agents.yml

- name: Deploy Portainer
  hosts: manager
  tasks:
    - include_tasks: ../roles/portainer/tasks/deploy_portainer.yml

- name: Create Endpoint charger
  hosts: localhost
  tasks:
    - include_tasks: ../roles/portainer/tasks/create_endpoint.yml
