- name: Install Prometheus
  hosts: swarm
  become: true
  vars:
    prometheus_version: "3.5.0"
    prometheus_arch_map:
      x86_64: amd64
      aarch64: arm64
    prometheus_install_dir: /opt/prometheus
  tasks:
    - include_tasks: ../roles/prometheus/tasks/install.yml