- name: Deploy stack postgres via Portainer API
  hosts: localhost
  vars:
    postgres_version: "17.5"
    stack_name: postgres
    stack_config: "{{ lookup('file', '../roles/postgres/files/postgres-stack.yml') }}"
    portainer_endpoint_name: charger
    repositoryURL: "https://github.com/Buchtl/charger-deployment.git"
    repositoryReferenceName: "refs/heads/portainer"
    composeFile: "stacks/postgres-stack.yml"
    stack_env:
      - name: "POSTGRES_VERSION"
        value: "{{ postgres_version }}"
  tasks:
    - include_tasks: ../roles/portainer/tasks/authenticate.yml
    - include_tasks: ../roles/portainer/tasks/endpoint_id.yml
    - include_tasks: ../roles/portainer/tasks/deploy_stack.yml
