#- name: Create password secret for postgres
#  hosts: manager
#  become: true
#  vars:
#    secret_name: "postgres_password"
#  tasks:
#    - name: Set secret_value fact from vault
#      set_fact:
#        secret_value: "{{ postgres_password }}"
#    - name: Setup postgres docker secrets
#      include_role:
#        name: swarm
#        tasks_from: docker_secret

- name: Create database for keycloak
  hosts: localhost
  vars:
    # New User
    postgres_new_user: "{{ postgres_charger_user }}"
    postgres_new_user_password: "{{ postgres_charger_password }}"
    # DB with new user as owner
    database_name: "{{ postgres_charger_user }}"
    database_owner: "{{ postgres_charger_password }}"
  tasks:
    - include_tasks: ../roles/postgres/tasks/create_user.yml
    - include_tasks: ../roles/postgres/tasks/create_database.yml


- name: Deploy stack postgres via Portainer API
  hosts: localhost
  vars:
    stack_name: charger-base
    portainer_endpoint_name: charger
    repositoryURL: "https://github.com/Buchtl/charger-base.git"
    #repositoryReferenceName: "{{ git_default_branch }}"
    composeFile: "docker/docker-compose.yml"
    stack_env:
      - name: "CHARGER_BASE_VERSION"
        value: "0.2-SNAPHSOT"
      - name: "CHARGER_BASE_ARCH"
        value: "ARM64"
      - name: "DB_URL"
        value: "postgres"
      - name: "DB_PORT"
        value: "5432"   
      - name: "DB_USER"
        value: "{{ postgres_charger_user }}"
      - name: "DB_PASSWORD"
        value: "{{ postgres_charger_password }}"
      - name: "DB_NAME"
        value: "{{ postgres_charger_user }}"
      - name: "POLLING_PERIOD"
        value: "10"
  tasks:
    - include_tasks: ../roles/portainer/tasks/authenticate.yml
    - include_tasks: ../roles/portainer/tasks/endpoint_id.yml
    - include_tasks: ../roles/portainer/tasks/deploy_stack.yml
