- name: Deploy stack postgres via Portainer API
  hosts: localhost
  vars:
    stack_name: keycloak
    portainer_endpoint_name: charger
    repositoryURL: "https://github.com/Buchtl/charger-deployment.git"
    repositoryReferenceName: "refs/heads/keycloak"
    composeFile: "stacks/keycloak-stack.yml"
    stack_env:
      - name: "KEYCLOAK_ADMIN"
        value: "admin"
      - name: "KEYCLOAK_ADMIN_PASSWORD"
        value: "admin"
      - name: "KC_DB"
        value: "postgres"
      - name: "KC_DB_URL"
        value: "jdbc:postgresql://postgres_db:5432/keycloak"
      - name: "KC_DB_USERNAME"
        value: "{{ postgres_keycloak_user }}"
      - name: "KC_DB_PASSWORD"
        value: "{{ postgres_keycloak_password }}"
      - name: "KC_HOSTNAME"
        value: "{{ ansible_hostname }}"

  tasks:
    - include_tasks: ../roles/portainer/tasks/authenticate.yml
    - include_tasks: ../roles/portainer/tasks/endpoint_id.yml
    - include_tasks: ../roles/portainer/tasks/deploy_stack.yml


