---
- name: Create cert-related secrets
  hosts: manager
  vars:
    version: "v2"
    secrets:
      - name: cert_key
        value: "{{ cert_key }}"
      - name: cert
        value: "{{ cert }}"
  tasks:
    - name: Create secret "{{ item.name }}_{{ version }}"
      include_role:
        name: swarm
        tasks_from: docker_secret
      loop: "{{ secrets }}"
      loop_control:
        loop_var: item
      vars:
        secret_name: "{{ item.name }}_{{ version }}"
        secret_value: "{{ item.value }}"
