- name: Deploy Portainer Stack
  hosts: swarm
  become: true
  
  vars:
    network_name: "charger-net"

  tasks:
    - name: Setup network "charger-net"
      include_role:
        name: swarm
        tasks_from: docker_network

- name: Create secret for cert key
  hosts: manager
  become: true
  vars:
    secret_name: "cert_key"
  tasks:
    - name: Set secret_value fact from vault
      set_fact:
        secret_value: "{{ cert_key }}"
    - name: Setup postgres docker secrets
      include_role:
        name: swarm
        tasks_from: docker_secret
